version: "3.8"

services:

  reader:
    build: .
    environment:
      - BYTEWAX_PYTHON_FILE_PATH=app.reader:flow
      - BYTEWAX_PYTHON_PARAMETERS=-p 2 -w 2
      - SUBSCRIPTION_NAME=reader # not used
      - OUTPUT_TOPIC=raw
    volumes:
      - ./apps/reader:/bytewax/app
      - ./data:/data
      - ./connectors:/bytewax/connectors
    depends_on:
      pulsar:
        condition: service_healthy
      contentparser:
        condition: service_started
      messagesink:
        condition: service_started
      eventsink:
        condition: service_started

  contentparser:
    build: .
    environment:
      - BYTEWAX_PYTHON_FILE_PATH=app.contentparser:flow
      - BYTEWAX_PYTHON_PARAMETERS=-p 3 -w 2
      - INPUT_TOPIC=raw
      - SUBSCRIPTION_NAME=contentparser
      - OUTPUT_TOPIC=parsed
    volumes:
      - ./apps/contentparser:/bytewax/app
      - ./connectors:/bytewax/connectors
      - ./ekeparser:/bytewax/ekeparser
    depends_on:
      pulsar:
        condition: service_healthy

  eventcreator:
    build: .
    environment:
      - BYTEWAX_PYTHON_FILE_PATH=app.eventcreator:flow
      - BYTEWAX_PYTHON_PARAMETERS=-p 2 -w 2
      - INPUT_TOPIC=parsed
      - SUBSCRIPTION_NAME=eventcreator
      - OUTPUT_TOPIC=events
    volumes:
      - ./apps/eventcreator:/bytewax/app
      - ./connectors:/bytewax/connectors
    depends_on:
      pulsar:
        condition: service_healthy

  messagesink:
    build: .
    environment:
      - BYTEWAX_PYTHON_FILE_PATH=app.pgsink:flow
      - BYTEWAX_PYTHON_PARAMETERS=-p 1 -w 2
      - INPUT_TOPIC=parsed
      - SUBSCRIPTION_NAME=messagesink
      - POSTGRES_CONN_STR=postgresql://postgres:password@db:5432/postgres
      - SINK_SCHEMA=MESSAGES
    volumes:
      - ./apps/pgsink:/bytewax/app
      - ./connectors:/bytewax/connectors
    depends_on:
      pulsar:
        condition: service_healthy
      db:
        condition: service_healthy

  eventsink:
    build: .
    environment:
      - BYTEWAX_PYTHON_FILE_PATH=app.pgsink:flow
      - BYTEWAX_PYTHON_PARAMETERS=-p 1 -w 2
      - INPUT_TOPIC=events
      - SUBSCRIPTION_NAME=messagesink
      - POSTGRES_CONN_STR=postgresql://postgres:password@db:5432/postgres
      - SINK_SCHEMA=EVENTS
    volumes:
      - ./apps/pgsink:/bytewax/app
      - ./connectors:/bytewax/connectors
    depends_on:
      pulsar:
        condition: service_healthy
      db:
        condition: service_healthy

  pulsar:
    image: "apachepulsar/pulsar:3.1.1"
    command: [ "bin/pulsar", "standalone" ]
    volumes:
      # - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: "timescale/timescaledb-ha:pg15.4-ts2.11.2-all"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # pulsardata:
  pulsarconf:
