global:
  scrape_interval: 10s

scrape_configs:
  - job_name: bytewax
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - ajoaikadata:3030
